deploy 3

diff --git a/.github/workflows/pages.yml b/.github/workflows/pages.yml
--- a/.github/workflows/pages.yml
+++ b/.github/workflows/pages.yml
@@ -2,7 +2,6 @@
 name: Deploy static SvelteKit content to Pages
 
 on:
-  # Runs on pushes targeting the default branch
   push:
     branches: ['main']
 
@@ -22,48 +21,64 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  build-site:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout
+      - name: Checkout 🛎️
         uses: actions/checkout@v3
 
-      - name: Install pnpm
-        uses: pnpm/action-setup@v2
-        with:
-          version: 8
+      - name: Detect package manager 👻
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
 
-      - name: Install Node.js
+      - name: Setup Node 🍉
         uses: actions/setup-node@v3
         with:
-          node-version: 18
-          cache: pnpm
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          node-version: '16.10.0'
 
-      - name: Install dependencies
-        run: pnpm i
-
-      - name: Setup Pages
-        uses: actions/configure-pages@v3
+      - name: Setup Pages 🔧
+        id: pages
+        uses: actions/configure-pages@v1
         with:
-          static_site_generator: 'sveltekit'
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: sveltekit
 
-      - name: Build site
-        run: pnpm run build
+      - name: Install dependencies 🥑
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
-      - name: Upload artifact
+      - name: Build with sveltekit 🍄
+        run: ${{ steps.detect-package-manager.outputs.runner }} run build
+
+      - name: Upload artifact ⛱️
         uses: actions/upload-pages-artifact@v1
         with:
-          path: 'build/'
+          path: ./build
 
   deploy:
-    needs: build-site
-    runs-on: ubuntu-latest
-
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-
+    runs-on: ubuntu-latest
+    needs: build
     steps:
-      - name: Deploy to GitHub Pages
+      - name: Deploy to GitHub Pages 🚀
         id: deployment
-        uses: actions/deploy-pages@v2
+        uses: actions/deploy-pages@v1
